Basic Python

1. Split this string

In [110]:
s = "Hi there Aran!"

In [111]:
s.split(" ")

['Hi', 'there', 'Aran!']

2. Use .format() to print the following string.

In [112]:
planet = "Moon"
diameter =  3474.8

In [113]:
print("the diameter of the {} is {} kilometers".format (planet,diameter))


the diameter of the Moon is 3474.8 kilometers


3. In this nest dictionary grab the word "hello"

In [114]:
d = {"k1":[1,2,3,{"tricky":["oh","man","inception",{"target":[1,2,3,"hello"]}]}]}


In [115]:
d["k1"][3]["tricky"][3]["target"][3]


'hello'

4. Numpy

In [116]:
import numpy as np


4.1 Create an array of 10 zeros?
4.2 Create an array of 10 fives?

In [117]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [118]:
np.zeros(10)+5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Create an array of all the even integers from 20 to 35

In [119]:
np.arange(20,35,2)


array([20, 22, 24, 26, 28, 30, 32, 34])

6. Create a 3x3 matrix with values ranging from 0 to 8

In [120]:
np.arange (0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Concatenate a and b

In [121]:
a=np.array([4,5,6])
b=np.array([7,3,8])

In [122]:
np.concatenate((a,b))


array([4, 5, 6, 7, 3, 8])

In [123]:
import pandas as pd


Pandas
8. Create a dataframe with 3 rows and 2 columns

In [124]:
data = np.arange(0,6).reshape(3,2)
df = pd.DataFrame(data)
df


0  1
0  0  1
1  2  3
2  4  5

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023


In [125]:
p = pd.date_range(start ='1-1-2023', 
         end ='10-02-2023') 
for val in p:
    print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00
2023-02-11 00:00:00
2023-02-12 00:00:00
2023-02-13 00:00:00
2023-02-14 00:00:00
2023-02-15 00:00:00
2023-02-16 00:00:00
2023-02-17 00:00:00
2023-02-18 00:00:00
2023-02-19 00:00:00


10. Create 2D list to DataFrame

In [126]:
lists=[[1, "aaa",25]],[[2,"bbb",22]],[[3,"ccc",23]]

In [127]:
df=pd.DataFrame(lists)
df


0
0  [1, aaa, 25]
1  [2, bbb, 22]
2  [3, ccc, 23]